"""Async SQLAlchemy setup.

A single async engine + session factory is created from `DATABASE_URL`. The
same model code runs against SQLite locally (`sqlite+aiosqlite`) and Postgres in
production (`postgresql+asyncpg`) — so avoid SQLite-only column types in models.
"""

from collections.abc import AsyncGenerator

from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

from backend.app.config import get_settings

settings = get_settings()

# `future=True` is the 2.0-style engine; echo follows the debug flag so SQL is
# visible during local development but silent in production.
engine = create_async_engine(
    settings.database_url,
    echo=settings.debug,
    future=True,
)

# expire_on_commit=False keeps ORM objects usable after a commit inside a
# request handler (a common FastAPI gotcha with async sessions).
AsyncSessionLocal = async_sessionmaker(
    bind=engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


class Base(DeclarativeBase):
    """Declarative base shared by all ORM models.

    Alembic imports this (via backend.app.models) so its metadata drives
    autogenerated migrations.
    """


async def get_db() -> AsyncGenerator[AsyncSession, None]:
    """FastAPI dependency that yields a scoped async session per request."""
    async with AsyncSessionLocal() as session:
        yield session
